---
title: "Análise Multivariada - Exercício 1"
author: "Seu Nome"
date: "2023-10-26"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# pacotes necessarios
library(tidyverse)  # contém os pacotes readr e dplyr, entre outros
library(corrplot)   # para usar a funcao corrplot()
library(FactoMineR) # para usar a funcao PCA()
library(factoextra) # para usar as funcoes fviz_pca_*
```


## Questões

### 1. Importação dos Dados

#### 1.1

```{r}
url <- "http://goo.gl/IQl8nc"
```

#### 1.2

```{r}

```


#### 1.3 



### 2. Preparação dos Dados

#### 2.1

```{r}
percepcao_df <- percepcao_marcas %>%
  dplyr::mutate(across(1:9, as.integer),
                across(10, as.factor))  
```

Verificando se a transformacão foi bem sucedida:

```{r}

```



### 3. Análise Exploratória dos Dados

```{r}
corrplot::corrplot(cor(percepcao_df[ , 1:9]) , order = "hclust")
```


### 4. Análise de Componentes Principais

#### 4.1 

```{r}

```



#### 4.2

```{r}

```



#### 4.3

```{r}

```



#### 4.4

```{r}

```



#### 4.5

```{r}

```











